[theme]
name = "plain"

[icons]
name = "awesome"

[[block]]
block = "disk_space"
path = "/"
alias = "Linux"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "battery"
interval = 2

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "net"
device = "enp7s0"
interval = 2
speed_up = true
graph_up = true

[[block]]
block = "net"
device = "wlp6s0"
speed_up = true
interval = 2

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"


